SELECT 1 = 1
UNION ALL
SELECT 'a' = 'b'
UNION ALL
SELECT 1 != 'a'
UNION ALL
SELECT 1 IS NULL
UNION ALL
SELECT null IS NULL OR col IS NULL
UNION ALL
SELECT col IS NULL
UNION ALL
SELECT NOT true
UNION ALL
SELECT random() XOR true
UNION ALL
SELECT true AND false OR false AND true